# Dump definitions from a docs.luduvo.com binding catalog snapshot. In the future, the globalTypes won"t be hardcoded

import json
import re
from pathlib import Path
# All Luduvo stuff is in its own folder as to not confuse it with the Roblox stuff
ROOT = Path(__file__).resolve().parents[1] / "luduvo"
rows = json.loads((ROOT / "luduvo-api.json").read_text())
components = json.loads((ROOT / "luduvo-components.json").read_text())
out = [
    "-- Luduvo API declarations. Source: https://docs.luduvo.com/reference",
    "-- Binding catalog version 4, retrieved 2026-09-12. Generated by scripts/luduvo/dumpLuduvoTypes.py.",
    "-- Components taken from the unofficial luduvo scripting docs",
    "-- Server/client availability and read-only restrictions are documented but not enforced by the LSP",
    "-- Dynamic component/event columns aren't inferred right now.",
    '',
    "type ComponentName = " + " | ".join(json.dumps(component) for component in components),
    "-- Note that ComponentName is not up to date with the latest Luduvo build so its not exposed yet.",
]

comment_flags = {
    8: "Server only.",
    16: "Read only at runtime.",
} # Bit shifted flags used in the Luduvo API docs

def gen_comment(row, indent=''):
    out.append(indent + "-- " + row["doc"].replace("\n", " "))
    for flag, text in comment_flags.items():
        if row["flags"] & flag:
            out.append(indent + "-- " + text)

def gen_signature(row, owner):
    type = row["type"]
    # A few binding signatures use Lua return colons and an untyped self so we check for them.
    type = re.sub(r"^\(self(?=[,)])", "(self: " + owner, type)
    depth = 0
    for i, c in enumerate(type):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                if type[i+1:].startswith(":"):
                    type = type[:i+1] + " ->" + type[i+2:]
                break
    if owner == "Instance" and row["flags"] & 7 == 2 and not type.startswith("(self:"):
        type = "(self: Instance" + (", " if not type.startswith("()") else '') + type[1:]
    return type

special = {
    "Component": "export type Component = { [string]: any }",
    "AnimLayers": "export type AnimLayers = { [number]: AnimLayerRow }",
    "EventColumn": "export type EventColumn<T = any> = { [number]: T }",
    "QueryColumn": "export type QueryColumn<T = any> = { [number]: T }",
}

if __name__ == "__main__":
    services = []

    for i, row in enumerate(rows):
        if row["parent"]:
            continue
        name, kind = row["name"], row["flags"] & 7
        """
        Kind 0: Instance (like the root). Should only be 1 of these
        Kind 1: Instance Properties
        Kind 2: Instance Methods/Functions
        Kind 3: Enums
        Kind 4: Game Services
        Kind 5: Global Classes (like Vector2, Vector3, Udim2, etc.)
        Kind 6: Grab bag of things that need special treatment
        """
        children = [row for row in rows if row["parent"] == i + 1]
        gen_comment(row)
        if kind in (2, 3) or (kind == 5 and row["type"]):
            out.append("declare " + name + ": " + row["type"])
        elif name in special and kind == 6:
            out.append(special[name])
        elif kind == 6 and not children:
            out.append("declare extern type " + name + " with end")
        else:
            owner = name + "Service" if kind == 4 else name
            if kind == 4:
                services.append((name, owner))
            prefix = "declare " if kind == 5 else "export type "
            sep = ": " if kind == 5 else " = "
            base = "Instance & " if kind == 4 and name == "World" else ''
            out.append(prefix + owner + sep + base + "{")
            if name in ("Query", "EventTable") and kind == 6:
                out.append("    -- Note that the exact Columns depend on the query terms or event schema.")
                out.append("    [string]: any,")
            if name == "Query" and kind == 6:
                # This stuff likely is outdated
                out.extend("    " + n + ": QueryColumn<vector>," for n in ("Position", "Scale", "BrickColor", "Velocity"))
                out.extend(["    PlayerSpawner: {character: QueryColumn<string>, respawnDelay: QueryColumn<number>},",
                            "    Tool: {equipped: QueryColumn<number>},"])
            for child in children:
                gen_comment(child, "    ")
                type = gen_signature(child, owner)
                if name == "Query" and child["name"] == "Entity":
                    type = "QueryColumn<Instance>"
                out.append("    " + child["name"] + ": " + type + ",")
            out.append("}")
        out.append('')

    out.append("declare game: {")
    out.extend("    " + name + ": " + type + "," for name, type in services)
    out.extend(["}", ''])
    (ROOT / "globalTypes.d.luau").write_text("\n".join(out), encoding="utf-8")

    print(f"Successfully dumped {len(rows)} entries and {len(services)} game services.")
