# Dump definitions from a docs.luduvo.com binding catalog snapshot. In the future, the globalTypes won"t be hardcoded

import json
import re
from pathlib import Path
# All Luduvo stuff is in its own folder as to not confuse it with the Roblox stuff
ROOT = Path(__file__).resolve().parent / "api-docs" / "en-us"
rows = json.loads((ROOT / "luduvo-api.json").read_text())
components = json.loads((ROOT / "luduvo-components.json").read_text())
component_overrides = json.loads((ROOT / "luduvo-component-overrides.json").read_text())
components = sorted(set(components + component_overrides), key=str.casefold)
api_overrides = json.loads((ROOT / "luduvo-api-overrides.json").read_text())
out = [
    "-- Luduvo API declarations. Source: https://docs.luduvo.com/reference",
    "-- Binding catalog version 4. Generated by scripts/luduvo/dumpLuduvoTypes.py.",
    "-- Engine component names are maintained in scripts/luduvo/api-docs/en-us/luduvo-components.json.",
    "-- Server/client availability and read-only restrictions are documented but not enforced by the LSP",
    "-- Event columns remain dynamic because their types depend on the declared schema.",
    '',
    "export type ComponentName = " + " | ".join(json.dumps(component) for component in components),
]

comment_flags = {
    8: "Server only.",
    16: "Read only at runtime.",
} # Bit shifted flags used in the Luduvo API docs

def gen_comment(row, indent=''):
    out.append(indent + "-- " + row["doc"].replace("\n", " "))
    for flag, text in comment_flags.items():
        if row["flags"] & flag:
            out.append(indent + "-- " + text)

def gen_signature(row, owner):
    type = row["type"]
    # A few binding signatures use Lua return colons and an untyped self so we check for them.
    type = re.sub(r"^\(self(?=[,)])", "(self: " + owner, type)
    depth = 0
    for i, c in enumerate(type):
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                if type[i+1:].startswith(":"):
                    type = type[:i+1] + " ->" + type[i+2:]
                break
    if owner == "Instance" and row["flags"] & 7 == 2 and not type.startswith("(self:"):
        type = "(self: Instance" + (", " if not type.startswith("()") else '') + type[1:]
    return type

special = {
    "Component": "export type Component = { [string]: any }",
    "AnimLayers": "export type AnimLayers = { [number]: AnimLayerRow }",
    "EventColumn": "export type EventColumn<T = any> = { [number]: T }",
    "QueryColumn": "export type QueryColumn<T = any> = { [number]: T }",
}

if __name__ == "__main__":
    services = []
    event_table_members = {
        "Event", "ToServer", "ToClients", "F32", "I32", "U8", "Bool", "Vec3", "Color", "Entity", "Prefab", "String"
    }

    for i, row in enumerate(rows):
        if row["parent"]:
            continue
        name, kind = row["name"], row["flags"] & 7
        if name in event_table_members:
            continue
        """
        Kind 0: Instance (like the root). Should only be 1 of these
        Kind 1: Instance Properties
        Kind 2: Instance Methods/Functions
        Kind 3: Enums
        Kind 4: Game Services
        Kind 5: Global Classes (like Vector2, Vector3, Udim2, etc.)
        Kind 6: Grab bag of things that need special treatment
        """
        children = [row for row in rows if row["parent"] == i + 1]
        children.extend(row for row in api_overrides if row["owner"] == name)
        gen_comment(row)
        if kind in (2, 3) or (kind == 5 and row["type"]):
            out.append("declare " + name + ": " + row["type"])
        elif name in special and kind == 6:
            out.append(special[name])
        elif kind == 6 and not children:
            out.append("declare extern type " + name + " with end")
        else:
            owner = name + "Service" if kind == 4 else name
            if kind == 4:
                services.append((name, owner))
            prefix = "declare " if kind == 5 else "export type "
            sep = ": " if kind == 5 else " = "
            out.append(prefix + owner + sep + "{")
            if name in ("Query", "EventTable") and kind == 6:
                out.append("    -- Note that the exact Columns depend on the query terms or event blueprint.")
                out.append("    [string]: any,")
            if name == "Query" and kind == 6:
                out.extend("    " + component + ": QueryColumn<any>," for component in components)
                # out.append("    [string]: QueryColumn<any>,") # Bring back when custom components are supported
            for child in children:
                gen_comment(child, "    ")
                type = gen_signature(child, owner)
                if name == "World" and child["name"] == "Query":
                    type = "(...ComponentName) -> Query"
                if name == "World" and child["name"] == "Each":
                    type = "(name: ComponentName) -> () -> Instance?"
                if name == "Query" and child["name"] in ("With", "Without"):
                    type = "(self: Query, name: ComponentName) -> Query"
                if name == "Query" and child["name"] == "Entity":
                    type = "QueryColumn<Instance>"
                if name == "Instance" and child["name"] in ("AddComponent", "HasComponent", "RemoveComponent"):
                    type = type.replace("name: string", "name: ComponentName", 1)
                if name == "Instance" and child["name"] == "attr":
                    type = "{ [string]: number | boolean | string | vector }"
                out.append("    " + child["name"] + ": " + type + ",")
            out.append("}")
        out.append('')

    out.extend([
        "export type EventTableFactory = ((name: string, direction: EventDirection, fields: {{string | EventFieldType}}) -> EventTable) & {",
        "    ToServer: EventDirection,",
        "    ToClients: EventDirection,",
        "    F32: EventFieldType,",
        "    I32: EventFieldType,",
        "    U8: EventFieldType,",
        "    Bool: EventFieldType,",
        "    Vec3: EventFieldType,",
        "    Color: EventFieldType,",
        "    Entity: EventFieldType,",
        "    Prefab: EventFieldType,",
        "    String: EventFieldType,",
        "}",
        "",
        "declare game: {",
    ])
    out.extend("    " + name + ": " + type + "," for name, type in services)
    out.extend([
        "    EventTable: EventTableFactory,",
        "}",
        "",
    ])
    (ROOT / "globalTypes.luduvo.d.luau").write_text("\n".join(out), encoding="utf-8")

    print(f"Successfully dumped {len(rows)} entries and {len(services)} game services.")
